name: AdminEye
main: nl.Steffion.AdminEye.AdminEye
version: 0.1.0_ALPHA
authors:
  - Steffion
load: POSTWORLD
commands:
  AdminEye:
    usage: /<command>
    description: N/A
    aliases:
        - ae
  ban:
    usage: /<command>
    description: N/A
    aliases:
        - kickban
  hp:
    usage: /<command>
    description: N/A
    aliases:
        - heal
        - h
  kick:
    usage: /<command>
    description: N/A
    aliases:
        - k
  slay:
    usage: /<command>
    description: N/A
    aliases:
        - kill
  unban:
    usage: /<command>
    description: N/A
    aliases:
        - uban
