name: AdminEye
main: nl.Steffion.AdminEye.AdminEye
version: 0.1.0_ALPHA
authors:
  - Steffion
load: POSTWORLD
commands:
  AdminEye:
    usage: /<command>
    description: N/A
    aliases:
        - ae
  kick:
    usage: /<command>
    description: N/A
    aliases:
        - k
  hp:
    usage: /<command>
    description: N/A
    aliases:
        - heal
        - h
  slay:
    usage: /<command>
    description: N/A
    aliases:
        - kill
  goto:
    usage: /<command>
    description: N/A
    aliases:
        - tp
  slap:
    usage: /<command>
    description: N/A
  bring:
    usage: /<command>
    description: N/A
    aliases:
        - summon
  feed:
    usage: /<command>
    description: N/A