name: AdminEye
main: nl.Steffion.AdminEye.AdminEye
version: 0.1.0_ALPHA
authors:
  - Steffion
  - RandomPanda30
load: POSTWORLD
commands:
  AdminEye:
    usage: /<command>
    description: N/A
    aliases:
        - ae
  ban:
    usage: /<command>
    description: N/A
    aliases:
        - kickban
  bring:
    usage: /<command>
    description: N/A
    aliases:
        - summon
        - s
        - tphere
  deop:
    usage: /<command>
    description: N/A
  hunger:
    usage: /<command>
    description: N/A
    aliases:
        - feed
  goto:
    usage: /<command>
    description: N/A
    aliases:
        - tp
        - teleport
  hp:
    usage: /<command>
    description: N/A
    aliases:
        - heal
        - h
  kick:
    usage: /<command>
    description: N/A
    aliases:
        - k
        - disconnect
  op:
    usage: /<command>
    description: N/A
  slap:
    usage: /<command>
    description: N/A
  slay:
    usage: /<command>
    description: N/A
    aliases:
        - kill
  unban:
    usage: /<command>
    description: N/A
    aliases:
        - uban
